[package]
name = "gravity-wars"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "z"

[dependencies]
cgmath = "0.16.1"
futures = "0.1.25"
gltf = "0.11"
js-sys = "0.3.5"
rgb = "0.8"
wasm-bindgen-futures = "0.3.5"

[dependencies.wasm-bindgen]
version = "0.2.28"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.5"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlUniformLocation",
    "Window",
]
