cargo-features = ["profile-overrides"]

[package]
name = "gravity-wars"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]

edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "z"

[profile.dev]
opt-level = 0

[profile.dev.overrides."*"]
opt-level = 2

[dependencies]
console_error_panic_hook = "0.1.5"
js-sys = "0.3.7"
nalgebra = "0.16.13"
rgb = "0.8"
serde_json = "1.0.34"

[dependencies.gltf]
version = "0.11"
features = ["extras"]

[dependencies.rand]
version = "0.6.4"
features = ["wasm-bindgen"]

[dependencies.wasm-bindgen]
version = "0.2.30"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.7"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlUniformLocation",
    "Window",
]
