cargo-features = ["profile-overrides"]

[package]
name = "gravity-wars"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]

edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "z"

[profile.dev]
opt-level = 0

[profile.dev.overrides."*"]
opt-level = 2

[dependencies]
console_error_panic_hook = "0.1.6"
js-sys = "0.3.14"
image = "0.19.0" # TODO: upgrade once gltf crate supports a newer version.
nalgebra = "0.17.2"
ncollide2d = "0.18.3"
num-complex = "0.2.1"
rgb = "0.8.13"
serde_json = "1.0.39"

[dependencies.gltf]
version = "0.11.3"
features = ["extras"]

[dependencies.rand]
version = "0.6.5"
features = ["wasm-bindgen"]

[dependencies.wasm-bindgen]
version = "0.2.37"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.10"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlTexture",
    "WebGlUniformLocation",
    "Window",
]
