[package]
name = "gravity-wars"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "z"

[dependencies]
cgmath = "0.16.1"
gltf = "0.11"
rgb = "0.8"
specs-derive = "0.3.0"

[dependencies.specs]
version = "0.14.0"
default-features = false

[dependencies.wasm-bindgen]
version = "0.2.27"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.2"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlUniformLocation",
    "Window",
]
