cargo-features = ["profile-overrides"]

[package]
name = "gravity-wars"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]

edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "z"

[profile.dev]
opt-level = 0

[profile.dev.overrides."*"]
opt-level = 2

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
futures = "0.1.26"
image = "0.21.1"
js-sys = "0.3.20"
log = "0.4.6"
nalgebra = "0.17.3"
ncollide2d = "0.18.4"
num-complex = "0.2.1"
rgb = "0.8.13"
serde_json = "1.0.39"
wasm-bindgen-futures = "0.3.20"

[dependencies.gltf]
version = "0.12.0"
features = ["extras"]

[dependencies.rand]
version = "0.6.5"
features = ["wasm-bindgen"]

[dependencies.wasm-bindgen]
version = "0.2.43"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.20"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Response",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlTexture",
    "WebGlUniformLocation",
    "Window",
]
