cargo-features = ["profile-overrides"]

[package]
name = "gravity-wars"
version = "0.1.0"
authors = ["Ben Merritt <blm768@gmail.com>"]

edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "z"

[profile.dev]
opt-level = 0

[profile.dev.overrides."*"]
opt-level = 2

[dependencies]
cgmath = "0.16.1"
gltf = "0.11"
js-sys = "0.3.5"
rgb = "0.8"

[dependencies.wasm-bindgen]
version = "0.2.29"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.6"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlActiveInfo",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlUniformLocation",
    "Window",
]
